### ISSUE TITLE
Pay Club - Ajustar Nombre archivo de Conciliación

### ISSUE THREAD

**Issue by gustavorios** [vtex/checkout-instore#22]
This Github issue is synchronized with Zendesk,

**Ticket ID:** [4109](https://vtexhelp.zendesk.com/agent/#/tickets/4109)
**Priority:** normal
**Group:** Prime
**Assignee:** Julian Cecchi

**Original ticket description:**

Buenas tardes, cordial saludo.

Pay Club solicitó ajustar la estructura del nombre que contiene  archivo de conciliación. Actualmente al ser descargado, contiene la siguiente estructura >> http://prntscr.com/7z3fdr

La correcta deberá ser: http://prntscr.com/7z3fid

Esto para una próxima certificación, será motivo de NO Go. Razón por la cual cobra importancia.

Muchas gracias.

**Comment by gustavorios** [comment]
*Comment made from Zendesk by Julian Cecchi on 2015-08-06 at 18:29:*

<div class="zd-comment">
<p>Buenas tardes adri,<br>
Para que cliente es y cual es el ambiente?</p>
<p>Cunha,<br>
Me ayudas a crear una task en Assana para el equipo de gateway por favor?</p>
<p>Saludos,<br>
Julian</p>
</div>

**Comment by gustavorios** [comment]
*Comment made from Zendesk by Adriana Rodriguez on 2015-08-06 at 18:39:*

<div class="zd-comment">
<p>Hola Juli, buenas tardes.</p>
<p>Esta estructura de archivo debe ser adoptada para todos los clientes que utilicen Pay Club en Ecuador, incluido Comandato.</p>
<p>Muchas gracias.</p>
</div>

**Comment by gustavorios** [comment]
*Comment made from Zendesk by Julian Cecchi on 2015-08-07 at 19:35:*

<div class="zd-comment">
<p>Hola rodrigo,<br>
Por favor me ayudas a crear una task assana para este issue?<br>
No tengo acceso y sin eso el team de Gateway no lo resolverá.</p>
<p>Aguardo tu feedback por favor.</p>
<p>Saludos,<br>
Julian</p>
</div>

**Comment by gustavorios** [comment]
*Comment made from Zendesk by Adriana Rodriguez on 2015-10-29 at 15:18:*

<div class="zd-comment">
<p>Hola Juli, ¿Alguna novedad sobre este caso por favor?</p>
<p>Agradezco tu ayuda y tu feedback. Tenemos en cola de certificación a SONY Ecuador y es necesario, cumplir con este item, por favor, gracias.</p>
</div>

**Comment by nevescode** [comment]
@gustavorios isso era pra ser aberto no checkout, não? acho que o zendesk abriu no lugar errado
