### ISSUE TITLE
Problemas con el registro de clientes (Codigo CEP)

### ISSUE THREAD

**Issue by gustavorios** [vtex/checkout-instore#23]
This Github issue is synchronized with Zendesk,

**Ticket ID:** [8522](https://vtexhelp.zendesk.com/agent/#/tickets/8522)
**Priority:** normal
**Group:** Blaze
**Assignee:** Adriana Rodriguez

**Original ticket description:**

Hola Adri, tenemos este caso con Totto, el cual el cliente dice que no puede realizar la compra por un error con la direccion de entrega, al revisar en el Master Data encontré que el problema es por el numero de código CEP que esta registrada su dirección:

Como puedes ver la ciudad registrada por el cliente es Villavicencio, pero el código CEP que muestra es 0020, cuando el código real de esta ciudad es 50001. Al corregir esto ya funciono como puedes ver en el siguiente pantallazo.

Puedes por favor ayudarme a revisar el porque sucede esto ya que es claro que el cliente selecciona la ciudad de un listado y el código nunca se digita para que esto este sucediendo.

Quedo atento a tu respuesta,

**Comment by gustavorios** [comment]
*Comment made from Zendesk by Adriana Rodriguez on 2015-10-15 at 20:56:*

<div class="zd-comment">
<p>Hola Joan, cómo estás?</p>
<p>De acuerdo a nuestra revisión vía skype del escenario, este escenario corresponde a un problema de plataforma, razón por la cual será direccionado a un problema conocido, cuyo ID es: <a href="/agent/tickets/8694" target="_blank" rel="ticket">#8694</a>, para que nuestro equipo de desarrollo pueda investigar y resolver.</p>
<p>Una vez esté resuelto, serás notificado, gracias.</p>
<p>Adriana Rz.</p>
</div>

**Comment by nevescode** [comment]
@gustavorios isso era pra ser aberto no checkout, não? acho que o zendesk abriu no lugar errado
