### ISSUE TITLE
identificação na tela do carrinho com algum item já adicionado não funciona

### ISSUE THREAD

**Issue by nevescode** [vtex/checkout-instore#56]
se eu tento me identificar após ter adicionado um item dá xabu

**Comment by fskinner** [comment]
Algum erro específico? A identificação só adiciona um "attachment" no OrderForm com seus dados... Se estiverem chamando o mesmo método que identifica no início do processo, em teoria, deveria funcionar...

**Comment by augustocb** [comment]
@resendefreitas pode ajudar?

**Comment by resendefreitas** [comment]
```Uncaught TypeError: Cannot read property 'pushState' of undefined```
this.props.history tá undefined. Vou tentar corrigir.

**Comment by resendefreitas** [comment]
Ué, ele da esse erro no console, porque não tem próxima página pra ir mesmo. Mas funciona, ele seta o email certinho.
